OBJECTS += \
	   Utilities/GL/gli.o \
	   Utilities/GL/gliCamera.o \
	   Utilities/GL/gliDataStructure.o \
	   Utilities/GL/gliPickBox.o \
	   Utilities/GL/gliTransTool.o \
	   Utilities/GL/gliFont.o
