# $Id$
#------------------------------------------------------
# Make your own and use it or use the one in BASELINE
#------------------------------------------------------

#-----------------------------------------------------------------------------
# Choose a compiler & its options
#--------------------------------------------------------------------------
 CC = CC

 CXX = CC

 OPTS = -n32 -LANG:std

 INCLUDE = -I/usr/local/include -I. -I../mathtool 

CFLAGS     = $(OPTS) $(INCLUDE) 
CXXFLAGS   = $(CFLAGS) 
TARGET = ../lib/libmodelgraph.so
all: $(TARGET)

#--------------------------------------------------------------------
.SUFFIXES: .cpp
.cpp.o:
	$(CC) ${CFLAGS} -c $<

% : %.o
	$(CXX) $(CXXFLAGS) -o $@ $@.cpp
#--------------------------------------------------------------------
OBJS = ModelGraph.o ModelNode.o ModelEdge.o

objs: ${OBJS}
#--------------------------------------------------------------------
$(TARGET): objs
	$(CC) -w -shared -no_unresolved -o $(TARGET) $(OBJS)
clean:
	rm -rf *.o $(TARGET) ii_files
