VIZMO_DIR=..
include $(VIZMO_DIR)/M_incl

ifeq ($(RPM), 0)
TARGET=$(VIZMO_DIR)/lib/libCD.a
else
TARGET=$(VIZMO_DIR)/lib/libCD.so
endif

OBJECTS = CollisionDetection.o

ifeq ($(RPM), 0)
$(TARGET): $(OBJECTS)
	ar ruv $@ $(OBJECTS)
#	libtool -static -o $@ $(OBJECTS)
else
$(TARGET): $(OBJECTS)
	$(CC) -shared $(OBJECTS) -Wl,-soname=`basename $@`.0 -o $@
endif


clean:
	rm -f ${TARGET} ${OBJECTS} Dependencies
	touch Dependencies

include Dependencies
