######################################################################
# Automatically generated by qmake (1.02a) Wed Sep 18 16:04:21 2002
######################################################################

TEMPLATE = app

# Input
HEADERS += gui.h main_win.h scene_win.h
SOURCES += gui.cpp main_win.cpp scene_win.cpp
