all:
	cd GL; make -f Makefile.sgi
	cd mathtool; make -f Makefile.sgi
	cd modelgraph; make -f Makefile.sgi
	cd src; make -f Makefile.sgi
	cd OBPRMView/src; make -f Makefile.sgi

clean:
	cd GL; make -f Makefile.sgi clean
	cd mathtool; make -f Makefile.sgi clean
	cd modelgraph; make -f Makefile.sgi clean
	cd src; make -f Makefile.sgi clean
	cd OBPRMView/src; make -f Makefile.sgi clean
