#
# RAPID.spec
#
# This is designed to build RAPID from the current
# Parasol SVN.  To create the source tarball, do:
#
# svn co svn+ssh://parasol-svn.cs.tamu.edu/research/parasol-svn/svnrepository/vizmo
# rm -rf `find vizmo -name .svn`
# mv vizmo/trunk vizmo++-0-`date +%Y.%m.%d`
# tar cvzf vizmo++-0-`date +%Y.%m.%d`.tar.gz vizmo++-0-`date +%Y.%m.%d`
#
%define date 2007.10.11
Name: vizmo++
Summary: vizmo++ - A visualization/authoring tool for motion planning 
Version: 0 
Release: %{date}%{dist}
License: Copyright 2006, Parasol Lab, Texas A&M University.  All Rights Reserved.
Group: Development/Tools
Source: %{name}-%{version}-%{date}.tar.gz
# CR_icra06.pdf from http://parasol.tamu.edu/publications/download.php?file_id=519
Source2: vizmo++-CR_icra06.pdf 
URL: http://parasol.tamu.edu/groups/amatogroup/research/vizmo++/
Packager: Jack Perdue <j-perdue@tamu.edu>, Parasol Laboratory, Texas A&M University -- http://parasol.tamu.edu/
BuildRoot: %{_tmppath}/%{name}-%{version}-%{date}-buildroot
Patch1: vizmo++-rpm.diff
Requires: RAPID qt4
BuildRequires: RAPID-devel qt4-devel

%description
VIZMO is a 3D visualization/authoring tool for files 
provided/generated by the OBPRM motion planning library. 
This new version of VIZMO, VIZMO++, was developed for 
visualizing and editing motion planning environments, 
problem instances, and their solutions. VIZMO++ offers 
a nice and easy to use graphical user interface (GUI) 
that allows you to display workspace environments, 
roadmap, path, and start/goal positions. It enables 
users to interact with and edit the environment. 

%prep
%setup -n %{name}-%{version}-%{date}
%patch1 
cp %{SOURCE2} .

%build
make -f Makefile.linux

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/bin
install %{name} %{buildroot}/usr/bin
mkdir -p %{buildroot}/usr/lib/vizmo++
cd lib
for file in `ls *.so` ; do
  install $file %{buildroot}/usr/lib/vizmo++/$file.%{version}.%{release}
done
cd ..

%clean
rm -rf %{buildroot}

%post
/sbin/ldconfig -n /usr/lib/vizmo++

%postun
/sbin/ldconfig -n /usr/lib/vizmo++
rmdir /usr/lib/vizmo++

%files
/usr/bin/%{name}
/usr/lib/%{name}
%doc vizmo++-CR_icra06.pdf

%changelog
* Thu Oct 11 2007 Jack Perdue <j-perdue@tamu.edu> 0-11oct2007 
- Initial version

# EOF - vizmo++.spec

