SRCMOC += $(patsubst SpaceMouse/%.h, SpaceMouse/MOC/moc_%.cpp, $(shell grep -l Q_OBJECT SpaceMouse/*.h))
SMOBJMOC = $(patsubst SpaceMouse/%.h, SpaceMouse/MOC/moc_%.o, $(shell grep -l Q_OBJECT SpaceMouse/*.h))

OBJECTS += \
  $(SMOBJMOC) \
  SpaceMouse/SpaceMouseManager.o

####### MOC
.SECONDARY: $(SRCMOC)
