OBJECTS += \
	   EnvObj/BoundingBoxParser.o \
	   EnvObj/BoundingBoxesModel.o \
	   EnvObj/QueryLoader.o \
	   EnvObj/QueryModel.o \
	   EnvObj/DebugLoader.o \
	   EnvObj/DebugModel.o \
	   EnvObj/Robot.o
