OBJECTS += \
	   EnvObj/BoundaryModel.o \
	   EnvObj/BoundingBoxModel.o \
	   EnvObj/BoundingSphereModel.o \
	   EnvObj/BoundingBoxParser.o \
	   EnvObj/BoundingBoxesModel.o \
	   EnvObj/PathLoader.o \
	   EnvObj/PathModel.o \
	   EnvObj/QueryLoader.o \
	   EnvObj/QueryModel.o \
	   EnvObj/DebugLoader.o \
	   EnvObj/DebugModel.o \
	   EnvObj/Robot.o
