VIZMO_DIR = ..

TARGET=../lib/libEnvObj.a

OBJS = BoundaryModel.o BoundingBoxModel.o BoundingSphereModel.o \
       BoundingBoxParser.o BoundingBoxesModel.o \
       PathLoader.o PathModel.o \
       QueryLoader.o QueryModel.o \
       DebugLoader.o  DebugModel.o \
       Robot.o

OBJECTS = $(OBJS) 

include $(VIZMO_DIR)/Makefile.VizmoDefaults
