#!/bin/sh
system=`uname -s`
if  [ $system = "Linux" ]
then
make -f Makefile.linux $*
fi
if  [ $system = "IRIX" ]
then
make -f Makefile.sgi $*
fi  
if  [ $system = "IRIX64" ]
then
make -f Makefile.sgi $*
fi    
