#!/bin/sh
export LD_LIBRARY_PATH=/pub/dsmft1/Software/sgi/tk8.3.2/unix/:/pub/dsmft1/Software/sgi/tcl8.3.2/unix/:/pub/dsmft1/Software/sgi/vtk31/lib:/pub/dsmft/CD-libs/sgi/CSTK/CSTK-1.22/cstk/lib:/pub/dsmft/CD-libs/sgi/VCLIP/lib:/pub/dsmft/CD-libs/sgi/RAPID/RAPID_v2_01:/pub/dsmft/VIZMO/Vizmo-1.601/
export TCL_LIBRARY=/pub/dsmft1/Software/sgi/tcl8.3.2/library
export TK_LIBRARY=/pub/dsmft1/Software/sgi/tk8.3.2/library
/pub/dsmft/VIZMO/Vizmo-1.601/vizmo.sgi

