#!/bin/sh 
#find the system
system=`uname -s`
if [ $system = "Linux" ]
then
   export VIZMO_DIR=/share/Vizmo
   export VIZMO_SO=VizmoLibLinux
   export LD_LIBRARY_PATH=$VIZMO_DIR/lib:/share/lib:/research/sunburn/dsmft/CD-libs/linux/VCLIP/lib:$LD_LIBRARY_PATH
   export VTK=/share/bin/vtk
fi
if [ $system = "IRIX" ]
then
   VIZMO_DIR=/pub/rlab4/burc/Vizmo
   LD_LIBRARY_PATH=/pub/dsmft1/Software/sgi/tk8.3.2/unix/:/pub/dsmft1/Software/sgi/tcl8.3.2/unix/:/pub/dsmft1/Software/sgi/vtk31/lib:/pub/dsmft/CD-libs/sgi/CSTK/CSTK-1.22/cstk/lib:/pub/dsmft/CD-libs/sgi/VCLIP/lib:/pub/dsmft/CD-libs/sgi/RAPID/RAPID_v2_01:$VIZMO_DIR/lib
   TCL_LIBRARY=/pub/dsmft1/Software/sgi/tcl8.3.2/library
   TK_LIBRARY=/pub/dsmft1/Software/sgi/tk8.3.2/library
   VIZMO_SO=VizmoLibSgi
   VTK=/pub/dsmft1/Software/sgi/vtk31/tcl/vtk
   export VIZMO_DIR LD_LIBRARY_PATH TCL_LIBRARY TK_LIBRARY VIZMO_SO VTK


fi

 
if [ $system = "IRIX64" ]
then
   VIZMO_DIR=/pub/rlab4/burc/Vizmo
   VIZMO_SO=VizmoLibSgi
   LD_LIBRARY_PATH=/pub/dsmft1/Software/sgi/tk8.3.2/unix/:/pub/dsmft1/Software/sgi/tcl8.3.2/unix/:/pub/dsmft1/Software/sgi/vtk31/lib:/pub/dsmft/CD-libs/sgi/CSTK/CSTK-1.22/cstk/lib:/pub/dsmft/CD-libs/sgi/VCLIP/lib:/pub/dsmft/CD-libs/sgi/RAPID/RAPID_v2_01:$VIZMO_DIR/lib
   TCL_LIBRARY=/pub/dsmft1/Software/sgi/tcl8.3.2/library
   TK_LIBRARY=/pub/dsmft1/Software/sgi/tk8.3.2/library
   VTK=/pub/dsmft1/Software/sgi/vtk31/tcl/vtk
   export VIZMO_DIR LD_LIBRARY_PATH TCL_LIBRARY TK_LIBRARY VIZMO_SO VTK
   
fi            
   $VTK $VIZMO_DIR/vizmo.exe $*
