VIZMO_DIR=..
include $(VIZMO_DIR)/M_incl

ifeq ($(RPM), 0)
TARGET = ../lib/libmathtool.a
else
TARGET = ../lib/libmathtool.so
endif

OBJS         =  EulerAngle.o  Gauss.o  Matrix.o  Basic.o Quaternion.o

ifeq ($(RPM), 0)
$(TARGET): ${OBJS}
	ar ruv $@ $(OBJS)
#	libtool -static -o $@ $(OBJS)
else
$(TARGET): ${OBJS}
	$(CC) -shared $(OBJS) -Wl,-soname=`basename $@`.0 -o $@
endif

clean:
	rm -f *.o $(TARGET) Dependencies
	touch Dependencies

include Dependencies
