# $Id: Makefile.linux, sept. 16 2002
#------------------------------------------------------
# Make your own and use it or use the one in BASELINE
#------------------------------------------------------

#-----------------------------------------------------------------------------
# Choose a compiler & its options
#--------------------------------------------------------------------------
 CC = g++

 CXX = g++

 OPTS = -O2 -MMD

 INCLUDE = -I/usr/local/include

 CFLAGS     = $(OPTS) $(INCLUDE) -I.
 CXXFLAGS   = $(CFLAGS) 
 
 TARGET = ../lib/libmathtool.a

all: $(TARGET)

#--------------------------------------------------------------------
.SUFFIXES: .cpp
.cpp.o:
	$(CC) ${CFLAGS} -c $<
	cat $*.d >> Dependencies
	rm -f $*.d

#--------------------------------------------------------------------
OBJS         =  EulerAngle.o  Gauss.o  Matrix.o  Basic.o Quaternion.o

objs: ${OBJS}
#--------------------------------------------------------------------
$(TARGET): objs
	ar cru $(TARGET) $(OBJS)
#	libtool -static -o $(TARGET) $(OBJS)
clean:
	rm -f *.o $(TARGET) Dependencies
	touch Dependencies

include Dependencies
