VIZMO_DIR=..
include $(VIZMO_DIR)/M_incl

TARGET=$(VIZMO_DIR)/lib/libCD.a

OBJECTS = CollisionDetection.o

$(TARGET): $(OBJECTS)
	ar ruv $@ $(OBJECTS)

clean:
	rm -f ${TARGET} ${OBJECTS} Dependencies
	touch Dependencies

include Dependencies