OBJECTS += \
	   Models/BoundingBoxModel.o \
	   Models/BoundaryModel.o \
	   Models/BoundingSphereModel.o \
	   Models/CfgModel.o \
	   Models/DebugModel.o \
	   Models/EdgeModel.o \
	   Models/EnvModel.o \
	   Models/PathModel.o \
	   Models/PolyhedronModel.o \
	   Models/QueryModel.o \
	   Models/Vizmo.o
